spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: non

server:
    port: 8000